<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/reduce_sum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tensorflow**

In [1]:
#출처 : https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=kmkim1222&logNo=220992490164

In [12]:
import tensorflow as tf
import numpy as np
x=np.arange(6).reshape(2,3)
print('x값',x)

x값 [[0 1 2]
 [3 4 5]]


In [15]:
sess=tf.compat.v1.Session() #tensorflow 2버전에서 1실행

In [33]:
with tf.compat.v1.Session() as sess:
  x=np.arange(6).reshape(2,3)
  x=tf.constant(x)
  print('x값',x)  
  y=sess.run(tf.reduce_sum(x))
  y2=sess.run(tf.reduce_sum(x,0))
  print('reduce_sum값',y)

x값 Tensor("Const_7:0", shape=(2, 3), dtype=int64)
reduce_sum값 15


In [36]:
print('axis=0, 열 기준으로 덧셈',y2)
print('3 : 0+3')
print('5 : 1+4')
print('7 : 2+5')

axis=0, 열 기준으로 덧셈 [3 5 7]
3 : 0+3
5 : 1+4
7 : 2+5


# **torch**

In [38]:
import torch
x=torch.tensor([[0,1,2],[3,4,5]])
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [39]:
y=torch.sum(x)
y

tensor(15)

In [40]:
y2=torch.sum(x,0)
y2

tensor([3, 5, 7])