<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/reduce_mean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tensorflow**

In [1]:
import tensorflow as tf

In [4]:
x=tf.constant([[1,1],[2,2]])
print('x값',x)

x값 tf.Tensor(
[[1 1]
 [2 2]], shape=(2, 2), dtype=int32)


In [5]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
sess=tf.compat.v1.Session() #tensorflow 2버전에서 1실행

In [12]:
import numpy as np
with tf.compat.v1.Session() as sess:
  x=tf.constant([[1,1],[2,2]])
  x2=tf.constant([[2.5,1],[3,2]])
  print('x값',x)  
  y=sess.run(tf.reduce_mean(x))
  print('reduce_mean값',y)

  y2=sess.run(tf.reduce_mean(x2))
  print('reduce_mean값',y2)

x값 Tensor("Const_8:0", shape=(2, 2), dtype=int32)
reduce_mean값 1
reduce_mean값 2.125


# **torch**

In [16]:
import torch
x=torch.tensor([[2.5, 1], [3, 2]])
x

tensor([[2.5000, 1.0000],
        [3.0000, 2.0000]])

In [17]:
y=torch.mean(x)
print('y값',y)

y값 tensor(2.1250)
