<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/tf_reduce_sumipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import torch
matrix = torch.range(0,15).reshape(4,4)
print('matrix값',matrix)

b=torch.sum(matrix)
print('b값',b)

matrix값 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
b값 tensor(120.)


<ipython-input-9-30fb05db9216>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  matrix = torch.range(0,15).reshape(4,4)


In [10]:
matrix2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
bb=torch.sum(matrix,axis=0)
bb

tensor([24., 28., 32., 36.])

# **tensorflow**

In [3]:
import tensorflow as tf
import numpy as np
matrix = tf.range(0,16,1)
matrix=tf.reshape(matrix,[4,4])
matrix2=np.zeros([4,4])
print('matrix값',matrix)

matrix값 tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32)


In [4]:
b=tf.reduce_sum(matrix)
print('b값',b)

b값 tf.Tensor(120, shape=(), dtype=int32)


In [5]:
bb=tf.reduce_sum(matrix, axis=0)
print('bb값',bb)

bb값 tf.Tensor([24 28 32 36], shape=(4,), dtype=int32)
