<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/sigmoid%2Czeros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **zeros**

In [8]:
import tensorflow as tf
a=tf.zeros([1,3])
print('a값',a)

import torch
b=torch.zeros([1,3])
print('b값',b)

c=torch.zeros([1,3],dtype=torch.float32)
print('c값',c)

a값 tf.Tensor([[0. 0. 0.]], shape=(1, 3), dtype=float32)
b값 tensor([[0., 0., 0.]])
c값 tensor([[0., 0., 0.]])


# **tf.Variable**

In [10]:
global_step = tf.Variable(0, trainable=False)
global_step

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>

In [15]:
a=torch.tensor(0,dtype=torch.int32)
a

tensor(0, dtype=torch.int32)

# **session.run(init) 응용**

In [23]:
import tensorflow as tf
matrix1=tf.constant([[3,3]])
matrix2=tf.constant([[2],[2]])

print('matrix1값',matrix1)

matrix1값 tf.Tensor([[3 3]], shape=(1, 2), dtype=int32)


In [25]:
product=tf.matmul(matrix1, matrix2)
print(product)

tf.Tensor([[12]], shape=(1, 1), dtype=int32)


In [34]:
matrix1=tf.constant([[3,3],[2,2]])
print('matrix1값',matrix1)
matrix2=tf.constant([[2,2],[3,4]])
product=tf.matmul(matrix1, matrix2)
print(product)

matrix1값 tf.Tensor(
[[3 3]
 [2 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[15 18]
 [10 12]], shape=(2, 2), dtype=int32)


In [30]:
import torch
def mat2(x,y):
  z=torch.matmul(x,y)
  return z

In [33]:
x=torch.tensor([[3,3],[2,2]])
y=torch.tensor([[2,2],[3,4]])

z=mat2(x,y)
print('z값',z)

z값 tensor([[15, 18],
        [10, 12]])


# **sigmoid**

In [38]:
import torch.nn as nn

m = nn.Sigmoid()
input = torch.randn(2)
print('input값',input)

output = m(input)
print('output값',output)

input값 tensor([1.3437, 0.3150])
output값 tensor([0.7931, 0.5781])


In [40]:
input2=tf.constant([1.3437, 0.315])
print('input2값',input2)

output=tf.sigmoid(input2)
print('output값',output)

input2값 tf.Tensor([1.3437 0.315 ], shape=(2,), dtype=float32)
output값 tf.Tensor([0.79309773 0.5781052 ], shape=(2,), dtype=float32)
