<a href="https://colab.research.google.com/github/kimheeseo/python/blob/main/p_165_p_177_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
class Relu:
  def __init__(self):
    self.mask=None

  def forward(self,x):
    self.mask=(x<=0)
    out=x.copy()
    print('out값:',out)
    out[self.mask]=0
    return out

  def backward(self,dout):
    dout[self.mask]=0
    dx=dout

In [1]:
x=[1,2,3,4,5]
y=x.copy()
y

[1, 2, 3, 4, 5]

In [4]:
import numpy as np
x=np.array([[1., -0.5], [-2,3]])
mask=(x<=0)
mask

# 역전파 때는 순전파 때 만들어둔 mask를 써서 mask의 원소가 True인 곳에는 상류에서 전파된 dout을 0으로 설정합니다.

array([[False,  True],
       [ True, False]])

In [20]:
# 내가 만든 relu함수
xx=[1, -0.5, -2.0, 3.0]
z = [0] * len(xx)


i=0
for i in range(len(xx)):
  if xx[i]>0:
    z[i]=xx[i]
    i=i+1
  else:
    z[i]=0
    i=i+1

z

[1, 0, 0, 3.0]

In [17]:
z = [0] * len(xx)
z

[0, 0, 0, 0]

In [18]:
z[0]

0

**Sigmoid**

In [21]:
class sigmoid:
  def __init__(self):
    self.out=None

  def forward(self,x):
    out=1/(1+np.exp(-x))
    self.out=out

    return out

  def backward(self,dout):
    dx=dout*(1.0-self.out)*self.out

    return dx

**Affine/Softmax 계층 구현하기**

In [24]:
# Affine 계층
# 신경망의 순전파에서는 가중치 신호의 총합을 계산하기 때문에, 행렬의 곱을 사용했습니다.

x=np.random.rand(2) # 입력
w=np.random.rand(2,3) # 가중치
b=np.random.rand(3) # 편향

x.shape
w.shape
b.shape

y=np.dot(x,w)+b
print('y값;',y)
print('x값;',x)
print('w값;',w)

y값; [0.92854464 1.11997431 0.71875925]
x값; [0.53899957 0.84144815]
w값; [[0.00908379 0.24817193 0.15344334]
 [0.39947575 0.55694632 0.70356565]]


In [25]:
# 신경망의 순전파 때 수행하는 행렬의 곱: 기하학에서는 affine transformation
x_dot_w=np.array([[0,0,0],[10,10,10]])
b=np.array([1,2,3])
print('x_dot_w값:',x_dot_w)
print('b값:',b)
print('x_dot_w+b값:',x_dot_w+b)

x_dot_w값: [[ 0  0  0]
 [10 10 10]]
b값: [1 2 3]
x_dot_w+b값: [[ 1  2  3]
 [11 12 13]]


In [26]:
dy=np.array([[1,2,3],[4,5,6]])
print('dy값:',dy)

db=np.sum(dy, axis=0)
print('db값:',db)

dy값: [[1 2 3]
 [4 5 6]]
db값: [5 7 9]


In [ ]:
class Affine:
  def __init__(self,w,b):
    self.w=w
    self.b=b
    self.x=None
    self.dw=None
    self.db=None

  def forward(self, x):
    self.x=x
    out=np.dot(x,self.w)+self.b

    return out

  def backward(self, dout):
    dx=np.dot(dout, self.w.T)
    self.dw=np.dot(self.x.T, dout)
    self.db=np.sum(dout, axis=0)

    return dx