<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/cast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tensorflow**

In [6]:
import tensorflow as tf
tf.random.set_seed(1)
logits=tf.random.uniform([2,2],maxval=10,dtype=tf.float32)
print('logits값',logits)

logits값 tf.Tensor(
[[1.6513085 9.014812 ]
 [6.309742  4.345461 ]], shape=(2, 2), dtype=float32)


In [7]:
print('before cast:',logits)

logits=tf.cast(logits, dtype=tf.int32)
print('after cast:',logits)
#float 32 -> int32

before cast: tf.Tensor(
[[1.6513085 9.014812 ]
 [6.309742  4.345461 ]], shape=(2, 2), dtype=float32)
after cast: tf.Tensor(
[[1 9]
 [6 4]], shape=(2, 2), dtype=int32)


# **torch**

In [17]:
a=torch.rand(2,2)
print('a값',a)
print('a.type값',a.dtype)

y=a.to(torch.int32)
print('변경된 a.type값',y.dtype)

a값 tensor([[0.2167, 0.0914],
        [0.7405, 0.5445]])
a.type값 torch.float32
변경된 a.type값 torch.int32
