<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/reduce_min_prod%2Cabs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tensorflow**

In [ ]:
import tensorflow as tf
a = tf.constant([
  [[1, 2], [3, 4]],
  [[1, 2], [3, 4]]
])
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
a

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
b = tf.constant([[1, 2, 7], [4, 5, 6]])
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 7],
       [4, 5, 6]], dtype=int32)>

In [ ]:
c=tf.reduce_min(b, axis=0)
d=tf.reduce_min(b, axis=1)
print('b값',b)
print('c값',c)
print('d값',d)

b값 tf.Tensor(
[[1 2 7]
 [4 5 6]], shape=(2, 3), dtype=int32)
c값 tf.Tensor([1 2 6], shape=(3,), dtype=int32)
d값 tf.Tensor([1 4], shape=(2,), dtype=int32)


# **torch**

In [ ]:
import torch
import torch.nn as nn
a = torch.tensor([[1, 2, 7], [4, 5, 6]])
a

tensor([[1, 2, 7],
        [4, 5, 6]])

In [ ]:
b=torch.min(a,1)
print('b값',b)

b값 torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))


In [ ]:
c=torch.min(a,0)
print('c값',c)

c값 torch.return_types.min(
values=tensor([1, 2, 6]),
indices=tensor([0, 0, 1]))


# **abs**

In [ ]:
a=tf.constant([-1,-2,-3,-5])
b=tf.abs(a)
print('b값',b)

b값 tf.Tensor([1 2 3 5], shape=(4,), dtype=int32)


In [ ]:
a=torch.tensor([-1,-2,-3,-5])
b=torch.abs(a)
print('b값',b)

b값 tensor([1, 2, 3, 5])


# **reduce_prod : tensorflow**

In [ ]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_prod(x)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
a=tf.math.reduce_prod(x, 0)
b=tf.math.reduce_prod(x, 1)
print('a값',a)
print('b값',b)

a값 tf.Tensor([3. 8.], shape=(2,), dtype=float32)
b값 tf.Tensor([ 2. 12.], shape=(2,), dtype=float32)


# **torch**

In [ ]:
x=torch.tensor([[1,2],[3,4]])
a=torch.prod(x,0)
a

tensor([3, 8])

In [ ]:
b=torch.prod(x,1)
b

tensor([ 2, 12])