<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/gather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tensorflow**

In [1]:
import tensorflow as tf
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
params

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]], dtype=float32)>

In [11]:
tf.gather(params, indices=[3,1,1,3]).numpy()

array([[30., 31., 32.],
       [10., 11., 12.],
       [10., 11., 12.],
       [30., 31., 32.]], dtype=float32)

# **torch**

In [5]:
import torch
x=torch.tensor([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print('x값',x)

x값 tensor([[ 0.,  1.,  2.],
        [10., 11., 12.],
        [20., 21., 22.],
        [30., 31., 32.]])


In [20]:
import numpy as np
y=np.zeros([4,3])
print('y값',y)
xx=[3,1,1,3]

for i in range(0,4):
  j=xx[i]
  y[i,:]=x[j,:]
print('y값',y)    

y값 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
y값 [[30. 31. 32.]
 [10. 11. 12.]
 [10. 11. 12.]
 [30. 31. 32.]]
