<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/tf_gather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

matrix = torch.range(0,99).reshape(10,10)
indices = [0,1,2,3,4,5,6,7,8,9]
indices = torch.tensor(indices).unsqueeze(axis=-1)
print(matrix)
print(indices)
print(torch.gather(matrix, 1, indices ))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
        [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
        [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
        [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
        [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
tensor([[ 0.],
        [11.],
        [22.],
        [33.],
        [44.],
        [55.],
        [66.],
        [77.],
        [88.],
        [99.]])


<ipython-input-1-87c65a4b2772>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  matrix = torch.range(0,99).reshape(10,10)


In [5]:
indices = torch.tensor(indices)
print('indices',indices)

indices tensor([[[[0]]],


        [[[1]]],


        [[[2]]],


        [[[3]]],


        [[[4]]],


        [[[5]]],


        [[[6]]],


        [[[7]]],


        [[[8]]],


        [[[9]]]])


<ipython-input-5-e55859b44559>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  indices = torch.tensor(indices)


In [13]:
import numpy as np
matrix = torch.range(0,99).reshape(10,10)
matrix2=np.zeros([10,10])
indices = [0,1,1,3,3,5,4,4,4,6]

for i in range(0,len(indices)):
  matrix2[i,:]=matrix[indices[i],:]

<ipython-input-13-3e19ae196f8b>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  matrix = torch.range(0,99).reshape(10,10)


In [14]:
matrix2

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.]])

# **tensorflow**

In [17]:
import tensorflow as tf
matrix = torch.range(0,99).reshape(10,10)
matrix2=np.zeros([10,10])
indices = [0,1,1,3,3,5,4,4,4,6]

<ipython-input-17-b9af6c7c57f5>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  matrix = torch.range(0,99).reshape(10,10)


In [18]:
matrix2=tf.gather(matrix, indices)
matrix2

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.]], dtype=float32)>