<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/stack%EC%97%B0%EC%8A%B5%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.__version__

'2.9.2'

# **tensorflow**

In [ ]:
import tensorflow as tf
x=tf.constant([1,4])
y=tf.constant([2,5])
z=tf.constant([3,6])
tf.stack([x,y,z])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

# **torch**

In [ ]:
import torch

In [ ]:
x=torch.tensor([1,4])
y=torch.tensor([2,5])
z=torch.tensor([3,6])
torch.stack([x,y,z])

tensor([[1, 4],
        [2, 5],
        [3, 6]])