<a href="https://colab.research.google.com/github/kimheeseo/python_summary/blob/main/stack3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
rods = tf.stack(prod_list) #####

NameError: ignored

# **tensorflow**

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tensor = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print("Tensor = ",tensor)
array = tensor.eval(session=tf.Session())
print("Array = ",array)

Instructions for updating:
non-resource variables are not supported in the long term


Tensor =  Tensor("Const:0", shape=(3, 3), dtype=int32)
Array =  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
rods=tf.stack(tensor)
rods

<tf.Tensor 'Const:0' shape=(3, 3) dtype=int32>

In [5]:
rod=tensor.eval(session=tf.Session())
rod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [4]:
rods2=tensor.eval(session=tf.Session())
rods2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

# **torch 버전**

In [ ]:
import torch
from torch.autograd import Variable
tensor2=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
tensor4=torch.stack([tensor2])
tensor4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])